import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useBookingStore } from "@/stores/booking.store";
import { CheckCircle2, Banknote, ArrowRight, Home } from "lucide-react";
export default function PaymentConfirmationPage() {
    const navigate = useNavigate();
    const { fareEstimate, driverInfo, clearBooking } = useBookingStore();
    const [confirmed, setConfirmed] = useState(false);
    const handleConfirm = () => {
        setConfirmed(true);
    };
    const handleDone = () => {
        clearBooking();
        navigate("/");
    };
    if (confirmed) {
        return (_jsxs("div", { className: "min-h-dvh bg-white flex flex-col items-center justify-center px-6 text-center", children: [_jsx("div", { className: "w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mb-6", children: _jsx(CheckCircle2, { size: 48, className: "text-green-600" }) }), _jsx("h1", { className: "text-2xl font-bold text-slate-900 mb-2", children: "Payment Confirmed" }), _jsx("p", { className: "text-slate-500 text-sm mb-2", children: "Cash payment of" }), _jsxs("p", { className: "text-3xl font-bold text-slate-900 mb-6", children: ["\u20B1", (fareEstimate?.total || 0).toFixed(2)] }), driverInfo && (_jsxs("p", { className: "text-sm text-slate-500 mb-8", children: ["Paid to ", driverInfo.name] })), _jsxs("button", { onClick: handleDone, className: "w-full max-w-xs h-12 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-2xl flex items-center justify-center gap-2 transition-colors", children: [_jsx(Home, { size: 18 }), "Back to Home"] })] }));
    }
    return (_jsxs("div", { className: "min-h-dvh bg-white flex flex-col", children: [_jsxs("div", { className: "px-6 pt-8 pb-6 text-center", children: [_jsx("div", { className: "w-14 h-14 bg-amber-100 rounded-2xl flex items-center justify-center mx-auto mb-4", children: _jsx(Banknote, { size: 28, className: "text-amber-600" }) }), _jsx("h1", { className: "text-xl font-bold text-slate-900", children: "Confirm Payment" }), _jsx("p", { className: "text-sm text-slate-500 mt-1", children: "Please confirm cash payment with your driver" })] }), _jsxs("div", { className: "flex-1 px-6 space-y-4", children: [_jsxs("div", { className: "bg-slate-50 rounded-2xl p-6 text-center", children: [_jsx("p", { className: "text-sm text-slate-500 mb-1", children: "Amount Due" }), _jsxs("p", { className: "text-4xl font-bold text-slate-900", children: ["\u20B1", (fareEstimate?.total || 0).toFixed(2)] })] }), driverInfo && (_jsxs("div", { className: "flex items-center gap-3 bg-slate-50 p-4 rounded-xl", children: [_jsx("div", { className: "w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center text-sm font-bold text-blue-600", children: driverInfo.name.charAt(0) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-slate-900", children: driverInfo.name }), _jsxs("p", { className: "text-xs text-slate-500", children: [driverInfo.vehicleType, " \u2022 ", driverInfo.plateNumber] })] })] })), fareEstimate && (_jsxs("div", { className: "space-y-2 text-sm", children: [_jsxs("div", { className: "flex justify-between text-slate-500", children: [_jsx("span", { children: "Trip Fare" }), _jsxs("span", { className: "text-slate-900", children: ["\u20B1", fareEstimate.tripFare.toFixed(2)] })] }), _jsxs("div", { className: "flex justify-between text-slate-500", children: [_jsx("span", { children: "Pickup Fee" }), _jsxs("span", { className: "text-slate-900", children: ["\u20B1", fareEstimate.pickupFee.toFixed(2)] })] }), _jsxs("div", { className: "flex justify-between text-slate-500", children: [_jsx("span", { children: "Platform Fee" }), _jsxs("span", { className: "text-slate-900", children: ["\u20B1", fareEstimate.platformFee.toFixed(2)] })] })] }))] }), _jsx("div", { className: "px-6 pb-8", children: _jsxs("button", { onClick: handleConfirm, className: "w-full h-13 bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white font-semibold rounded-2xl flex items-center justify-center gap-2 transition-colors shadow-lg shadow-blue-600/25 text-[15px]", children: ["I Have Paid Cash", _jsx(ArrowRight, { size: 18 })] }) })] }));
}
